### ISSUE TITLE
Build fails with gtk-3.16

### ISSUE THREAD

**Issue by pSub** [kragniz/sails#18]
Sails currently does not compile with gtk-3.16:

```
/tmp/nix-build-sails-0.1.1.drv-0/sails-0.1.1/sail_application.c: In function 'main':
79/tmp/nix-build-sails-0.1.1.drv-0/sails-0.1.1/sail_application.c:298:9: error: 'gtk_widget_set_double_buffered' is deprecated (declared at /...-gtk+3-3.16.2/include/gtk-3.0/gtk/gtkwidget.h:896) [-Werror=deprecated-declarations]
80         gtk_widget_set_double_buffered(window, FALSE);
81         ^
82cc1: all warnings being treated as errors
```
http://hydra.nixos.org/build/22693472/nixlog/1

**Comment by pSub** [comment]
To fix the build temporarily I have added the `-Wno-error` flag in  NixOS/nixpkg@4d70496ebb38796fea4f5c81079e031efb3fd959

**Comment by kragniz** [comment]
Thanks for the bug report. This will be fixed in the next release.
